sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t mrobinson108/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true mrobinson108/react-docker npm run test
